ignityLinks/urls.py
from django.conf.urls import patterns, include, url
from ignityLinks import views
from ignityLinks.views import RegistrarNovoForm, RegistrarNovoUsuarioForm, index, perfillogado, clicalink, apagalink
from django.contrib.auth.models import User


urlpatterns = patterns('',
	url(r'^$', views.home, name="home-page"),
	url(r'precos/$', views.precos, name="precos"),
	url(r'entrar/$', views.login, name="logar"),	
	url(r'registrar', RegistrarNovoForm.as_view(), name="registrar"),
	url(r"^login/$", "django.contrib.auth.views.login", {"template_name":"login.html"}, name="login"),
	url(r"^novo-usuario/$", RegistrarNovoUsuarioForm.as_view(), name="novo-usuario"),
	url(r"^logout/$", "django.contrib.auth.views.logout_then_login", {"login_url":"/login/"}, name="logout"),
	url(r"^user/(?P<perfil_nome>\w+)$", views.exibirlinks, name="exibirlinks"),
	url(r"^id?", views.perfillogado, name="login"),
	url(r"^apaga/(?P<link_id>\d+)$", views.apagalink, name="apagalink"),
	url(r"^click/(?P<link_id>\d+)$", views.clicalink, name="clicalink"),

	
)
	

projectI/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('ignityLinks.urls')),

)

ignityLinks/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms


class NovoLink(models.Model):
    titulo = models.CharField(max_length=255, null=False)
    url=models.CharField(max_length=255, null=False)
    data_criacao=models.CharField(max_length=255, null=False)
    usuario=models.ForeignKey(User, related_name="usuario")
    cliques=models.IntegerField(max_length=10, null=False) #descobrir como colocar valor inicial padrao=0

    def esconder(self):
    	exibe=True
    	pass   # adicionar código do toggle de exibe/esconde

    def incrementaClique(self):
        self.cliques=self.cliques+1
   

class NovoForm(forms.Form):
	titulo=forms.CharField(required=True)
	url=forms.CharField(required=True) 

	#adicionar validações do formulário nessa classe

class RegistrarUsuario(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.CharField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    
    def is_valid(self):
        valid=True
        if not super(RegistrarUsuario, self).is_valid():
            self.adiciona_erro("Por favor, verifique os dados informados")
            valid=False

        user_exists = User.objects.filter(username=self.data["nome"]).exists()
        if user_exists:
            self.adiciona_erro("Usuario ja existente")
            valid=False

        return valid


    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone=models.CharField(max_length=15, null=False)
    usuario=models.OneToOneField(User, related_name="perfil")

    @property
    def email(self):
        return self.usuario.email

ignityLinks/views.py
from django.shortcuts import render, redirect
from ignityLinks.models import NovoLink, NovoForm, RegistrarUsuario, Perfil
from django.views.generic import View
from django.contrib.auth.models import User
import datetime

def perfillogado(request):
    perfillog=get_perfil_logado(request)
    usuario= User.objects.get(username=perfillog.usuario.username)
    return render(request,"adicionalinks.html", {"novo_link": NovoLink.objects.filter(usuario=usuario), "perfis" : Perfil.objects.all(), "perfil_logado":get_perfil_logado(request)})

#def criaLinks(request):
 #   return render(request,"adicionalinks.html")

def index(request, perfil_id):
    return render(request,"adicionalinks.html", {"perfis" : Perfil.objects.all(), "perfil_logado":get_perfil_logado(request)})

def get_perfil_logado(request):
	return request.user.perfil

def login(request):
	return render(request,"login.html")	

def home(request):
    return render(request,"index.html")	

def precos(request):
    return render(request,"precos.html")	

def criaNovoLink(request):
    return render(request,"quasela.html")

class RegistrarNovoForm(View):

    template_name="adicionalinks.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
	    form = NovoForm(request.POST)
	    titulo=form.data["nomeUrl"]
	    url=form.data["linkUrl"]

	    perfillog=get_perfil_logado(request)
	    perfil=get_perfil_logado(request)
	    usuario= User.objects.get(username=perfillog.usuario.username)

	    novo_link = NovoLink(
				titulo=titulo, 
				url=url,
				data_criacao=datetime.datetime.now(),
				usuario=usuario,
				cliques=0
				)

	    novo_link.save()
	    return render(request,"adicionalinks.html", {"perfil" : perfil,"novo_link":NovoLink.objects.filter(usuario=usuario)})

class RegistrarNovoUsuarioForm(View):
	
	template_name="novo_registro.html"

	def get(self, request):
		return render(request, self.template_name)

	def post (self, request):
		form = RegistrarUsuario(request.POST)

		if form.is_valid():
			dados_form = form.data
			usuario= User.objects.create_user(dados_form["nome"],dados_form["email"], dados_form["senha"])

			perfil = Perfil(
				nome=dados_form["nome"], 
				email=dados_form["email"],
				telefone=dados_form["telefone"],
				usuario=usuario
				)

			perfil.save();

			return redirect("logar")

		return render(request, self.template_name, {"form": form})	


def exibirlinks(request, perfil_nome):
    
    perfil=Perfil.objects.get(nome=perfil_nome) # sintaxe pra buscar no banco de dados o perfil de perfil_id
    perfillog=get_perfil_logado(request)
    usuario= User.objects.get(username=perfillog.usuario.username)
    
    return render(request, "links.html", { "perfil" : perfil, "lista_links":NovoLink.objects.filter(usuario=usuario)})

def apagalink(request, link_id): #melhorar esse código, do jeito que está links estão expostos e podem ser facilmente apagados
    
    link_id=int(link_id) # converte string em número, para a query abaixo funcionar
    link=NovoLink.objects.get(id=link_id)
    link.delete()

    perfillog=get_perfil_logado(request)
    perfil=get_perfil_logado(request)
    usuario= User.objects.get(username=perfillog.usuario.username)
    
    return render(request,"adicionalinks.html", {"perfil" : perfil,"novo_link":NovoLink.objects.filter(usuario=usuario)})

def clicalink(request, link_id): #melhorar esse código, do jeito que está links estão expostos e podem ser facilmente apagados
    
    link_id=int(link_id) # converte string em número, para a query abaixo funcionar
    link=NovoLink.objects.get(id=link_id)
    link.incrementaClique()
    link.save()

    perfillog=get_perfil_logado(request)
    perfil=get_perfil_logado(request)
    usuario= User.objects.get(username=perfillog.usuario.username)

    return render(request, "links.html", { "perfil" : perfil, "lista_links":NovoLink.objects.filter(usuario=usuario)})

ignityLinks/templates/adicionalinks.html
{% extends "base.html" %}

{% block body%}


<section class="mbr-section form1 cid-rx4PrnCkBg" id="form1-d">
<br>
<br>
<br>
<br>

    

    
    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
                <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">Crie novos links</h2>
                
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="media-container-column col-lg-8 " data-form-type="formoid">
                <!---Formbuilder Form--->
                <form action="{% url "registrar" %}" method="POST" class="mbr-form form-with-styler">
				{% csrf_token %}
                    <div class="row">
                        

                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                        </div>
                    </div>
                    <div>
                        <div class="col-md-10  form-group" data-for="name">
                            <input id="nomeUrl" name="nomeUrl" type="text" placeholder="Título do site" class="form-control display-7 align-center">
                        </div>
                        <div class="col-md-10  form-group" data-for="email">
                            <input id="linkUrl" name="linkUrl" type="text" placeholder="Http/Url do site"  class="form-control display-7 align-center">
                        </div>
                                              
                        <div class="col-md-12 input-group-btn align-center">
                        	<button type="submit" class="btn btn-form btn-secondary display-3">Salvar no meu InstaGinga</button>
                        
                        	<button id="botaoApagar" class="btn btn-form display-7 botaoApagar">Limpar</button></div>
                    </div>
                </form><!---Formbuilder Form--->
            </div>
        </div>
    </div>
    <br>
</section>

<section class="mbr-section content4 cid-rx5p9scDJF" id="content4-i">

    
	{% if novo_link %}
    
	<!--<div class="container">
    	<div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
                <h3 class="mbr-section-title align-center pb-3 mbr-fonts-style display-5">Comece a cadastrar seus links acima!</h3>
                
            </div>
        </div>
    	</div> -->

    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-md-8">
                <h2 class="align-center pb-3 mbr-fonts-style display-5">Cole esse link na Bio do seu Instagram:&nbsp;</h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-fonts-style display-5"><a href="/user/{{user.perfil.nome}}" target="_blank" class="text-warning"><strong>
                    instagin.ga/user/{{user.perfil.nome}}
                </strong></a></h3>               
            </div>
        </div>
    </div>
    <br>
    <br>
	<div class="row justify-content-center">
        <div class="title col-12 col-lg-8">
    	    <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">Seus links atuais:</h2>
                
        </div>
    </div>

    <div class="lista-outputs item-lista">
			{% for link in novo_link %}
                    <div class="mbr-section-btn pt-3 align-center">
                        <a href="http://{{link.url}}" class="btn btn-warning-outline display-4" target="_blank">
                            {{link.titulo}}
                        </a>
                    </div>
                    <div class="mbr-section-title align-center pb-3 mbr-fonts-style">
						<span class="botao-deletar"><a class="botao-deletar" href="{% url "apagalink" link.id %}">Apagar esse link</a></span> 
					</div>
					<div class="mbr-section-title align-center pb-3 mbr-fonts-style">
						<span class="botao-deletar">Total de cliques: {{link.cliques}}</span> 
					</div>
		
        	{% endfor %}
		</div>


    {% else %}
    	<div class="container">
    	<div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
                <h3 class="mbr-section-title align-center pb-3 mbr-fonts-style display-5">Comece a cadastrar seus links acima!</h3>
                
            </div>
        </div>
    	</div>
       
    {% endif %}
</section>

<!-- código antido do mecanismo de criar e mostrar os novos links

	<div class="container">

		<!--<button id="adicionar-link" class="btn btn-lg btn-primary btn-block">Adicionar novo link!</button> -->
<!--
		<ul class="lista-links">

			<form class="form-signin" action="{% url "registrar" %}" method="post">
				{% csrf_token %}
				<input id="nomeUrl" name="nomeUrl" type="text" placeholder="Título do site" class="campoUrl form-control">
				<input id="linkUrl" name="linkUrl" type="text" placeholder="Http/Url do site" class="linkUrl form-control">
				<button id="botaoAdicionar" type="submit" class="botaoAdicionar btn btn-lg btn-block">Salvar Link no meu Ignity!</button>
				<button id="botaoApagar" class="botaoApagar btn btn-lg btn-block">Limpar</button> 

			</form>
				
		</ul>

		<br>

		{% if novo_link %}
		<h4 class="titulo-secundario">Cole esse link na Bio do seu Instagram: <a href="/user/{{user.perfil.nome}}"  target="_blank"> www.ignity.com.br/user/{{user.perfil.nome}}</a></h4>
		<div class="lista-outputs item-lista">
			{% for link in novo_link %}
			<form action="http://{{link.url}}" target="_blank" class="form-botao-externo">
				<button class="botaoExterno btn btn-lg btn-block" type="submit">{{link.titulo}}</button>
			</form>
				<span class="botao-deletar"><a href="{% url "apagalink" link.id %}">Apagar esse link</a></span> 
        	{% endfor %}
		</div>	

	   {% else %}
       <p>Comece a cadastrar seus links acima!</p>
       {% endif %}
	
	</div> 
-->





{% endblock %}

ignityLinks/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html  >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" type="image/x-icon" href="{% static "assets/images/dancing-122x122.png" %}">
  <meta name="description" content="">
  
  <title>InstaGinga: sua melhor chance no Instagram!</title>
  <link rel="stylesheet" href="{% static "assets/web/assets/mobirise-icons/mobirise-icons.css"%}">
  <link rel="stylesheet" href="{% static "assets/tether/tether.min.css"%}">
  <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.min.css"%}">
  <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap-grid.min.css"%}">
  <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap-reboot.min.css"%}">
  <link rel="stylesheet" href="{% static "assets/socicon/css/styles.css"%}">
  <link rel="stylesheet" href="{% static "assets/dropdown/css/style.css"%}">
  <link rel="stylesheet" href="{% static "assets/theme/css/style.css"%}">
  <link rel="stylesheet" href="{% static "assets/mobirise/css/mbr-additional.css"%}" type="text/css">
  
  
  
</head>
<body>
  <section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-0">

    

    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url "login" %}">
                         <img src="{% static "assets/images/dancing-122x122.png" %}"  alt="Minha Home" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href=""{% url "login" %}">
                        INSTAGIN.GA</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="/user/{{user.perfil.nome}}"  target="_blank"><span class="mbri-sale mbr-iconfont mbr-iconfont-btn"></span>
                        
                        InstaGinga de {{user.perfil.nome}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{% url "logout" %}"><span class="mbri-rocket mbr-iconfont mbr-iconfont-btn"></span>
                        
                        Log-out</a>
                </li></ul>
    </nav>
</section>



{% block body %}
{% endblock %}

<section class="cid-qTkAaeaxX5" id="footer1-2">

    

    

    <div class="container">
        <div class="media-container-row content text-white">
            <div class="col-12 col-md-3">
                <div class="media-wrap">
                    <a href="{% url "home-page" %}">
                        <img src="{% static "assets/images/dancing-192x192.png" %}" alt="InstaGinga" title="">
                    </a>
                </div>
            </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
                <h5 class="pb-3">
                    Endereço</h5>
                <p class="mbr-text">Orgulhosamente feito em São Paulo - Brasil :)</p>
            </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
                <h5 class="pb-3">
                    Contato</h5>
                <p class="mbr-text">
                    Email: atendimento@instagin.ga&nbsp;<!--<br>WhatsApp: +11 9999 - 9999<br>--></p>
            </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
                <h5 class="pb-3">
                    Links Úteis</h5>
                <p class="mbr-text"><a href="http://to-come.com" class="text-secondary">Dúvidas Adicionais?</a><br><a href="http://linktocome.com" class="text-secondary">Suporte para Clientes</a>&nbsp;<br><br></p>
            </div>
        </div>
        <div class="footer-lower">
            <div class="media-container-row">
                <div class="col-sm-12">
                    <hr>
                </div>
            </div>
            <div class="media-container-row mbr-white">
                <div class="col-sm-6 copyright">
                    <p class="mbr-text mbr-fonts-style display-7">
                        © Copyright 2019 Instagin.ga - Todos os direitos reservados</p>
                </div>
                <div class="col-md-6">
                    <div class="social-list align-right">
                        <div class="soc-item">
                            <a href="https://instagram.com/instaginga" target="_blank">
                                <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


  <script src="{% static "assets/web/assets/jquery/jquery.min.js"%}"></script>
  <script src="{% static "assets/popper/popper.min.js"%}"></script>
  <script src="{% static "assets/tether/tether.min.js"%}"></script>
  <script src="{% static "assets/bootstrap/js/bootstrap.min.js"%}"></script>
  <script src="{% static "assets/smoothscroll/smooth-scroll.js"%}"></script>
  <script src="{% static "assets/touchswipe/jquery.touch-swipe.min.js"%}"></script>
  <script src="{% static "assets/parallax/jarallax.min.js"%}"></script>
  <script src="{% static "assets/viewportchecker/jquery.viewportchecker.js"%}"></script>
  <script src="{% static "assets/vimeoplayer/jquery.mb.vimeo_player.js"%}"></script>
  <script src="{% static "assets/dropdown/js/nav-dropdown.js"%}"></script>
  <script src="{% static "assets/dropdown/js/navbar-dropdown.js"%}"></script>
  <script src="{% static "assets/theme/js/script.js"%}"></script>
  <script src="{% static "assets/web/assets/jquery/jquery.min.js"%}"></script>
  <script src="{% static "assets/popper/popper.min.js"%}"></script>
  <script src="{% static "assets/tether/tether.min.js"%}"></script>
  <script src="{% static "assets/bootstrap/js/bootstrap.min.js"%}"></script>
  <script src="{% static "assets/smoothscroll/smooth-scroll.js"%}"></script>
  <script src="{% static "assets/dropdown/js/nav-dropdown.js"%}"></script>
  <script src="{% static "assets/dropdown/js/navbar-dropdown.js"%}"></script>
  <script src="{% static "assets/touchswipe/jquery.touch-swipe.min.js"%}"></script>
  <script src="{% static "assets/theme/js/script.js"%}"></script>
   <script src="{% static "scripts/adicionaForm.js" %}"></script>  
  
</body>
</html>




<!-- Versão antiga do Base.html logado

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "styles/main.css" %}">
        <link rel="stylesheet" href="{% static "styles/ignity.css" %}">
        <title>Ignity</title>
    </head>
    <body>
        <div class="container">
            
            <div class="header">
            <ul class="nav nav-pills pull-right">
                <li><a href="{% url "login" %}">{{user.perfil.nome}}</a></li>
                <li><a href="{% url "logout" %}">LOGOUT</a></li>
            </ul>
            
            <h3 class="text-muted">Ignity</h3>
 
         <h1 class="titulo-principal">Sua melhor chance no Instagram</h1>

        </div>

        <div class="row content">
   
        </div>
    
    </body>
</html>

-->

ignityLinks/templates/links.html
{% load staticfiles %}



<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
        <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "styles/main.css" %}">
        <link rel="stylesheet" href="{% static "assets/web/assets/mobirise-icons/mobirise-icons.css"%}">
        <link rel="stylesheet" href="{% static "assets/tether/tether.min.css"%}">
        <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.min.css"%}">
        <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap-grid.min.css"%}">
        <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap-reboot.min.css"%}">
        <link rel="stylesheet" href="{% static "assets/socicon/css/styles.css"%}">
        <link rel="stylesheet" href="{% static "assets/dropdown/css/style.css"%}">
        <link rel="stylesheet" href="{% static "assets/theme/css/style.css"%}">
        <link rel="stylesheet" href="{% static "assets/mobirise/css/mbr-additional.css"%}" type="text/css">
        <link rel="stylesheet" href="{% static "styles/ignity.css" %}">

        <title>Links de {{perfil.nome}}</title>
    </head>
    <body>
        <div class="container">
            
            <div class="header">
              

        <!--<img class="pull-right" src="{% static "assets/images/dancing-122x122.png" %}"  alt="Minha Home" title="" style="height: 3.8rem;"> -->
         <h4 class="text-muted pull-right">InstaGin.ga</h4>

 

         <h4 class="text-muted">Links de {{perfil.nome}}</h4>

     </div>
     <br>


         <div class="lista-outputs">
            <ul>

                {% for link in lista_links %}


                <li class="item-lista">
                
                <div onclick="abreJanela('{{link.url}}')" class="abre-janela")>
                    <form action="{% url "clicalink" link.id %}" method="post" class="form-botao-externo">
                    {% csrf_token %}    
                    <!--<button class="botaoExterno btn btn-lg btn-block link-externo">{{link.titulo}}</button> -->
                    <!--<div class="col-md-12 align-center">
                            <button type="submit" class="btn btn-form btn-secondary display-2 botaoExterno">{{link.titulo}}</button>
                    </div> -->

                    <div class="row">
                        <div class="col four">
                            <a href="{% url "clicalink" link.id %}" class="btn btn-twitter">{{link.titulo}}</a>
                        </div>
                    </div>

                    </form>
                    <!-- <span class="alinhamento">
                    <span class="num-cliques">Número de Cliques:{{link.cliques}} <span class="numero-cliques"></span></span>
                    <span class="num-likes">Likes: </span>
                    </span> -->
                </div>
                </li>
                {% endfor %}
            </ul>
        </div>


       <script src="../static/scripts/abreJanela.js"></script>     
   
    </body>
</html>

ignityLinks/templates/mostralinks.html
{% extends "base.html" %}

{% block body%}
	<div class="container">
		<h1 class="titulo">Meu IGNITY!</h1>



{% endblock %}

ignityLinks/templates/novo_registro.html
{% extends "basedeslog.html" %}

{% block body %}
    <section class="mbr-section form1 cid-rx4PrnCkBg" id="form1-d">
	<br>
	<br>
	<br>
	<br>
	<br>
	    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
			    <h1 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">Sua melhor chance no Instagram</h1>                               
            </div>
            <div class="title col-12 col-lg-8">
			    <h3 class="mbr-section-title align-center pb-3 mbr-fonts-style display-4">Crie seu usuário grátis e melhore seus resultados
				</h3>                               
            </div>
        </div>
    </div>

        
    <div class="container">
        <div class="row justify-content-center">
            <div class="media-container-column col-lg-8" data-form-type="formoid">
             
                <!---Formbuilder Form--->
                <form action="{% url "novo-usuario" %}"  method="POST" class="mbr-form form-with-styler" data-form-title="Mobirise Form"><input type="hidden" name="login" value="me6B3Fe5w2GD/g7OD4xeJyK/cidDzJurGVlB+9iBNrGDd+LicXG5CAwuQ0cR5MuRlCSG8GOw1bknPmYu12emC7hfVhaavdec/tuNVHRXdjygvoNReno7J8OXJti27WIW">
                {% csrf_token %}
                    <div class="row">
                        
                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                        </div>
                    </div>
                    <div class="dragArea row">
                        <div class="col-md-6  form-group" data-for="name">
                            <label for="name-form1-d" class="form-control-label mbr-fonts-style display-7">Email</label>
                            <input id="id_email" name="email" type="text" data-form-field="Name" class="form-control display-7" placeholder="nome@email.com" value="{{form.email.value}}" required>
                        </div>

                        <div class="col-md-6  form-group" data-for="name">
                            <label for="name-form1-d" class="form-control-label mbr-fonts-style display-7">Seu Login</label>
                            <input  class="form-control display-7" id="id_nome" name="nome" type="text"placeholder="insira seu nome de usuário" value="{{form.nome.value}}" required>
                        </div>

                        <div class="col-md-6  form-group" data-for="password">
                            <label for="email-form1-d" class="form-control-label mbr-fonts-style display-7">Senha</label>
                            <input class="form-control display-7" id="id_senha" name="senha" type="password" placeholder="insira sua senha" required >
                        </div>                        

                        <div class="col-md-6  form-group" data-for="name">
                            <label for="email-form1-d" class="form-control-label mbr-fonts-style display-7">Telefone</label>
                            <input class="form-control display-7" id="id_telefone" name="telefone" type="text" placeholder="(xx)xxxx-xxxxx" value="{{form.telefone.value}}">
                        </div>

                       
                        
                        <div class="col-md-12 input-group-btn align-center"><button type="submit" class="btn btn-primary btn-form display-4">Criar Nova Conta</button></div>
                        <input type="hidden" name="next" value="{{ next }}" />
                        <br>
                        <br>
                        <br>
                        <br>
        
                    </div>
                </form><!---Formbuilder Form--->
            </div>
        </div>
    </div>
</section>


<!-- Código do form antigo

<!--	<form class="form-signin" action="{% url "novo-usuario" %}" method="post">
		{% csrf_token %}
		<h3 class="form-signin-heading">Crie seu usuário grátis e melhore seus resultados no Instagram</h3>

		<input id="id_email" name="email" type="text" class="form-control" placeholder="nome@email.com" value="{{form.email.value}}" required>
		<input id="id_nome" name="nome" type="text" class="form-control" placeholder="insira seu nome de usuário" value="{{form.nome.value}}" required>
		<input id="id_senha" name="senha" type="password" class="form-control" placeholder="insira sua senha" required>
		<input id="id_telefone" name="telefone" type="text" class="form-control" placeholder="(xx)xxxx-xxxxx (vamos precisar caso você perda sua senha)" value="{{form.telefone.value}}">
		
		<hr>

		{% if form.errors %}
			<div class="alert alert-danger">
				<button type="button" class="close">&times;</button>
				{{form.non_field_errors}}
			</div>
		{% endif %}


		<button class="btn btn-lg btn-primary btn-block" type="submit">Crie seu Ignity!</button>
	</form> -->
{% endblock %}